sudo: required
language: python
matrix:
    include:
        - python: 3.5
        - python: 3.4
before_install:
    - pip install codecov
install:
    - pip install -r requirements.txt
    - pip install -e .
script: sleep 10 && py.test -v
after_success: codecov
notifications:
  slack: blueoctober:bK5ntSOAiT0NfQEw4QUCQJAM
